services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: epta_user
      POSTGRES_PASSWORD: epta_password
      POSTGRES_DB: epta
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
    driver: local